### ISSUE TITLE
[BUG] 5* and 6* art missing

### ISSUE THREAD

**Issue by YummYume** [wesngu28/rhodesapi#5]
Hello, thanks for making this, very useful!

Operators (only 5* and 6*) on the `/operator` endpoint seem to have outdated or invalid art links. If I try to retrieve them one by one, though, it works.

PS : arts were working fine yesterday

**Comment by wesngu28** [comment]
I deleted the key in Redis. While rewriting some code I accidentally overwrote all those and redis must've cached a bad response, should be proper again
