### ISSUE TITLE
Some outdated/wrong information I found

### ISSUE THREAD

**Issue by vsadeghy** [wesngu28/rhodesapi#8]
- Ashlock and U-Official release_dates.global is "N/A". (for U-Official it's N/A in [gamepress](https://gamepress.gg/arknights/operator/u-official) too)
- Same with Kirin R Yato. Uses the old name (Kirin X Yato). Voicelines are in Chinese.
- Młynar voicelines are still in chinese. I believe it's the only operator (besides Kirin R Yato) that's released globally but has Chinese voicelines. I wonder why.

Great Project BTW

**Comment by wesngu28** [comment]
The internal change of the url from kirin-x-yato to kirin-r-yato which is what I check likely broke the means of updating Yalter's voicelines. Mylnar has a new skin which apparently adds custom voicelines so the EN ones were being overwritten by those. Both of these cases should be resolved.

The Ashlock and U-Official ones are a gamepress issue, I could hard-code their entries but I think its more likely gamepress should resolve them, especially for an older one like Ashlock.
